//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionMatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Intervention
    {
        public int idInter { get; set; }
        public System.DateTime datePlanifie { get; set; }
        public string Commentaire { get; set; }
        public int C_idMat { get; set; }
    
        public virtual Materiel Materiel { get; set; }
    }
}
